services:
  polling_service:
    build: .
    container_name: polling_service
    env_file:
      - .env
    ports:
      - "8000:8000" # доступ к приложению
      - "8001:8001" # метрики
    depends_on:
      - polling_rabbitmq
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: always
    command: poetry run python -m app.main

  polling_rabbitmq:
    image: rabbitmq:3-management
    container_name: polling_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASS}",
        "--save",
        "--appendonly",
        "yes",
      ]
    restart: always

  # OBSERVABILITY

  polling_prometheus:
    image: prom/prometheus:latest
    container_name: polling_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus

  polling_grafana:
    image: grafana/grafana:latest
    container_name: polling_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana

volumes:
  rabbitmq_data:
  prometheusdata:
  grafanadata:
